import type { Response } from "express";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { formatINR, paiseToRupees } from "@amiri/shared";
import { env } from "../config/env.js";

/**
 * Report export (§53, §54).
 *
 * One description of a report, three renderings. A report is described once as columns and
 * rows, then written as CSV, Excel or PDF — so a figure cannot appear one way on screen
 * and another in the file somebody emails to their accountant.
 *
 * Every format carries the same provenance block, which is what §53 and §54 are really
 * asking for: an exported figure is worthless if nobody can tell what it covered, who
 * produced it and when. A spreadsheet of numbers with no date range is a liability.
 */

export type ColumnAlign = "left" | "right" | "center";

export interface ExportColumn<T> {
  key: string;
  header: string;
  /** `money` values are integer paise and are rendered per format. */
  type?: "text" | "money" | "date" | "number";
  align?: ColumnAlign;
  width?: number;
  value: (row: T) => string | number | null | undefined;
  /** Include this column in the totals row. */
  total?: boolean;
}

export interface ExportSpec<T> {
  /** File name without extension. */
  filename: string;
  title: string;
  subtitle?: string;
  columns: Array<ExportColumn<T>>;
  rows: T[];

  /** The provenance block — §54's header requirements. */
  meta: {
    organisation: string;
    branch?: string;
    from?: Date;
    to?: Date;
    asOf?: Date;
    generatedBy: string;
    filters?: Record<string, string | undefined>;
  };

  /** Extra summary lines beneath the table: net profit, difference, tally status. */
  summary?: Array<{ label: string; value: string; emphasis?: boolean }>;
}

export type ExportFormat = "csv" | "xlsx" | "pdf";

/* -------------------------------------------------------------------------- */
/* Shared helpers                                                             */
/* -------------------------------------------------------------------------- */

function formatDate(date: Date | undefined): string {
  if (!date) return "";
  return date.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

/** The provenance lines, identical across all three formats. */
function metaLines(meta: ExportSpec<unknown>["meta"]): Array<[string, string]> {
  const lines: Array<[string, string]> = [];

  if (meta.branch) lines.push(["Branch", meta.branch]);
  if (meta.from && meta.to) {
    lines.push(["Period", `${formatDate(meta.from)} to ${formatDate(meta.to)}`]);
  } else if (meta.asOf) {
    lines.push(["As at", formatDate(meta.asOf)]);
  }

  for (const [key, value] of Object.entries(meta.filters ?? {})) {
    if (value) lines.push([key, value]);
  }

  lines.push(["Generated by", meta.generatedBy]);
  lines.push(["Generated at", new Date().toLocaleString("en-IN")]);

  return lines;
}

function cellValue<T>(column: ExportColumn<T>, row: T): string | number | null {
  const raw = column.value(row);
  if (raw === null || raw === undefined) return null;

  if (column.type === "money") {
    // Exported as RUPEES, not paise. A spreadsheet column of 12510100 that means
    // ₹1,25,101 is a trap — someone will sum it and be out by a factor of a hundred.
    return paiseToRupees(Number(raw));
  }
  return raw;
}

function totalsFor<T>(spec: ExportSpec<T>): Map<string, number> {
  const totals = new Map<string, number>();
  for (const column of spec.columns) {
    if (!column.total) continue;
    let sum = 0;
    for (const row of spec.rows) sum += Number(column.value(row) ?? 0);
    totals.set(column.key, column.type === "money" ? paiseToRupees(sum) : sum);
  }
  return totals;
}

/* -------------------------------------------------------------------------- */
/* CSV                                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Escape a CSV field.
 *
 * The leading-character guard is a security control, not formatting: a field starting
 * `=`, `+`, `-` or `@` is interpreted as a FORMULA when the file is opened in Excel, and a
 * party named `=cmd|'/c calc'!A1` becomes code execution on the machine of whoever opens
 * the export. Prefixing with a single quote neutralises it while still displaying the
 * original text.
 */
function csvField(value: string | number | null): string {
  if (value === null || value === undefined) return "";
  let text = String(value);

  if (/^[=+\-@\t\r]/.test(text)) text = `'${text}`;
  if (/[",\n\r]/.test(text)) text = `"${text.replace(/"/g, '""')}"`;

  return text;
}

function renderCsv<T>(spec: ExportSpec<T>): string {
  const lines: string[] = [];

  lines.push(csvField(spec.meta.organisation));
  lines.push(csvField(spec.title));
  if (spec.subtitle) lines.push(csvField(spec.subtitle));
  for (const [label, value] of metaLines(spec.meta)) {
    lines.push(`${csvField(label)},${csvField(value)}`);
  }
  lines.push("");

  lines.push(spec.columns.map((c) => csvField(c.header)).join(","));
  for (const row of spec.rows) {
    lines.push(spec.columns.map((c) => csvField(cellValue(c, row))).join(","));
  }

  const totals = totalsFor(spec);
  if (totals.size > 0) {
    lines.push(
      spec.columns
        .map((c, i) => (i === 0 ? csvField("TOTAL") : csvField(totals.get(c.key) ?? "")))
        .join(","),
    );
  }

  if (spec.summary?.length) {
    lines.push("");
    for (const item of spec.summary) lines.push(`${csvField(item.label)},${csvField(item.value)}`);
  }

  // A UTF-8 BOM, so Excel renders ₹ and Devanagari correctly instead of mojibake.
  return `﻿${lines.join("\r\n")}`;
}

/* -------------------------------------------------------------------------- */
/* Excel                                                                      */
/* -------------------------------------------------------------------------- */

async function renderXlsx<T>(spec: ExportSpec<T>): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = spec.meta.organisation;
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(spec.title.slice(0, 30), {
    // Repeat the header row on every printed page.
    views: [{ state: "frozen", ySplit: 0 }],
  });

  const titleRow = sheet.addRow([spec.meta.organisation]);
  titleRow.font = { bold: true, size: 14 };
  sheet.addRow([spec.title]).font = { bold: true, size: 12 };
  if (spec.subtitle) sheet.addRow([spec.subtitle]).font = { italic: true, size: 10 };

  for (const [label, value] of metaLines(spec.meta)) {
    const row = sheet.addRow([label, value]);
    row.font = { size: 9, color: { argb: "FF666666" } };
  }
  sheet.addRow([]);

  const headerRowIndex = sheet.rowCount + 1;
  const header = sheet.addRow(spec.columns.map((c) => c.header));
  header.font = { bold: true, color: { argb: "FFFFFFFF" } };
  header.eachCell((cell) => {
    cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF1E293B" } };
    cell.alignment = { vertical: "middle" };
  });

  for (const row of spec.rows) {
    const values = spec.columns.map((c) => cellValue(c, row));
    const added = sheet.addRow(values);

    spec.columns.forEach((column, i) => {
      const cell = added.getCell(i + 1);
      if (column.type === "money") {
        // A real Excel number with Indian grouping — the recipient can sum the column,
        // which is the entire reason for exporting to a spreadsheet rather than a PDF.
        cell.numFmt = '##,##,##0.00;[Red]-##,##,##0.00';
        cell.alignment = { horizontal: "right" };
      } else if (column.align) {
        cell.alignment = { horizontal: column.align };
      }
    });
  }

  const totals = totalsFor(spec);
  if (totals.size > 0) {
    const totalRow = sheet.addRow(
      spec.columns.map((c, i) => (i === 0 ? "TOTAL" : (totals.get(c.key) ?? null))),
    );
    totalRow.font = { bold: true };
    totalRow.eachCell((cell, col) => {
      cell.border = { top: { style: "thin" } };
      if (spec.columns[col - 1]?.type === "money") {
        cell.numFmt = '##,##,##0.00;[Red]-##,##,##0.00';
      }
    });
  }

  if (spec.summary?.length) {
    sheet.addRow([]);
    for (const item of spec.summary) {
      const row = sheet.addRow([item.label, item.value]);
      if (item.emphasis) row.font = { bold: true };
    }
  }

  spec.columns.forEach((column, i) => {
    sheet.getColumn(i + 1).width = column.width ?? Math.max(12, column.header.length + 4);
  });

  sheet.autoFilter = {
    from: { row: headerRowIndex, column: 1 },
    to: { row: headerRowIndex, column: spec.columns.length },
  };

  // ExcelJS declares its own Buffer type from an older @types/node; going through
  // `unknown` avoids a structural mismatch that has nothing to do with the bytes.
  return Buffer.from((await workbook.xlsx.writeBuffer()) as unknown as ArrayBuffer);
}

/* -------------------------------------------------------------------------- */
/* PDF                                                                        */
/* -------------------------------------------------------------------------- */

/**
 * PDF (§54).
 *
 * Header carries the organisation, report name and range; the footer carries who
 * generated it, when, and a page number. Both repeat on every page, because a page torn
 * out of a report has to remain identifiable.
 *
 * NOTE on the rupee sign: the built-in Helvetica has no ₹ glyph and would render a blank
 * box, so PDF amounts are prefixed "Rs." instead. Shipping a font file just for one glyph
 * is not worth the weight, and a blank box where a currency symbol should be is worse
 * than an unambiguous abbreviation.
 */
function renderPdf<T>(spec: ExportSpec<T>, res: Response): void {
  const doc = new PDFDocument({ size: "A4", layout: "landscape", margin: 36 });
  doc.pipe(res);

  const pageWidth = doc.page.width - 72;
  const totals = totalsFor(spec);

  const widths = spec.columns.map((c) => c.width ?? 100);
  const widthSum = widths.reduce((a, b) => a + b, 0);
  const scaled = widths.map((w) => (w / widthSum) * pageWidth);

  const money = (value: number): string => `Rs. ${formatINR(value, { symbol: false })}`;

  const drawHeader = (): void => {
    doc.fontSize(14).font("Helvetica-Bold").text(spec.meta.organisation, 36, 30);
    doc.fontSize(11).font("Helvetica-Bold").text(spec.title, 36, 48);
    if (spec.subtitle) doc.fontSize(9).font("Helvetica").text(spec.subtitle, 36, 64);

    let y = spec.subtitle ? 78 : 64;
    doc.fontSize(8).font("Helvetica").fillColor("#555555");
    for (const [label, value] of metaLines(spec.meta)) {
      doc.text(`${label}: ${value}`, 36, y);
      y += 10;
    }
    doc.fillColor("#000000");

    doc.moveTo(36, y + 4).lineTo(doc.page.width - 36, y + 4).strokeColor("#cccccc").stroke();
    doc.y = y + 12;
  };

  const drawColumnHeaders = (): void => {
    const y = doc.y;
    doc.rect(36, y - 2, pageWidth, 16).fill("#1e293b");
    doc.fillColor("#ffffff").fontSize(8).font("Helvetica-Bold");

    let x = 36;
    spec.columns.forEach((column, i) => {
      doc.text(column.header, x + 3, y + 2, {
        width: scaled[i]! - 6,
        align: column.align ?? (column.type === "money" ? "right" : "left"),
        lineBreak: false,
      });
      x += scaled[i]!;
    });

    doc.fillColor("#000000");
    doc.y = y + 18;
  };

  const drawRow = (row: T, striped: boolean): void => {
    const y = doc.y;
    if (y > doc.page.height - 60) {
      doc.addPage();
      drawHeader();
      drawColumnHeaders();
    }

    const top = doc.y;
    if (striped) doc.rect(36, top - 1, pageWidth, 14).fill("#f5f5f4").fillColor("#000000");

    doc.fontSize(8).font("Helvetica");
    let x = 36;
    spec.columns.forEach((column, i) => {
      const raw = column.value(row);
      const text =
        column.type === "money" && raw !== null && raw !== undefined
          ? money(Number(raw))
          : raw === null || raw === undefined
            ? ""
            : String(raw);

      doc.text(text, x + 3, top + 2, {
        width: scaled[i]! - 6,
        align: column.align ?? (column.type === "money" ? "right" : "left"),
        lineBreak: false,
        ellipsis: true,
      });
      x += scaled[i]!;
    });

    doc.y = top + 14;
  };

  drawHeader();
  drawColumnHeaders();
  spec.rows.forEach((row, i) => drawRow(row, i % 2 === 1));

  if (totals.size > 0) {
    const top = doc.y + 2;
    doc.moveTo(36, top).lineTo(doc.page.width - 36, top).strokeColor("#333333").stroke();
    doc.fontSize(8).font("Helvetica-Bold");

    let x = 36;
    spec.columns.forEach((column, i) => {
      const text =
        i === 0
          ? "TOTAL"
          : totals.has(column.key)
            ? column.type === "money"
              ? `Rs. ${formatINR(Math.round(totals.get(column.key)! * 100), { symbol: false })}`
              : String(totals.get(column.key))
            : "";
      doc.text(text, x + 3, top + 4, {
        width: scaled[i]! - 6,
        align: column.align ?? (column.type === "money" ? "right" : "left"),
        lineBreak: false,
      });
      x += scaled[i]!;
    });
    doc.y = top + 18;
  }

  if (spec.summary?.length) {
    doc.moveDown(0.5);
    for (const item of spec.summary) {
      doc.fontSize(9).font(item.emphasis ? "Helvetica-Bold" : "Helvetica");
      doc.text(`${item.label}: ${item.value}`, 36, doc.y);
    }
  }

  // Footer on every page, added after layout so the page count is known.
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(range.start + i);
    doc.fontSize(7).font("Helvetica").fillColor("#666666");
    doc.text(
      `${spec.meta.organisation} · ${spec.title} · generated by ${spec.meta.generatedBy} on ${new Date().toLocaleString("en-IN")}`,
      36,
      doc.page.height - 28,
      { width: pageWidth - 60, lineBreak: false },
    );
    doc.text(`Page ${i + 1} of ${range.count}`, doc.page.width - 110, doc.page.height - 28, {
      width: 74,
      align: "right",
      lineBreak: false,
    });
  }

  doc.end();
}

/* -------------------------------------------------------------------------- */
/* Entry point                                                                */
/* -------------------------------------------------------------------------- */

export async function sendExport<T>(
  res: Response,
  format: ExportFormat,
  spec: ExportSpec<T>,
): Promise<void> {
  const stamp = new Date().toISOString().slice(0, 10);
  const filename = `${spec.filename}-${stamp}`;

  // Quoted and sanitised: an unescaped filename is a header-injection vector, and a
  // report name containing a comma otherwise truncates the header.
  const safe = filename.replace(/[^\w.-]+/g, "_");

  switch (format) {
    case "csv": {
      res.setHeader("content-type", "text/csv; charset=utf-8");
      res.setHeader("content-disposition", `attachment; filename="${safe}.csv"`);
      res.send(renderCsv(spec));
      return;
    }

    case "xlsx": {
      const buffer = await renderXlsx(spec);
      res.setHeader(
        "content-type",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      );
      res.setHeader("content-disposition", `attachment; filename="${safe}.xlsx"`);
      res.send(buffer);
      return;
    }

    case "pdf": {
      res.setHeader("content-type", "application/pdf");
      res.setHeader("content-disposition", `attachment; filename="${safe}.pdf"`);
      renderPdf(spec, res);
      return;
    }

    default:
      throw new Error(`Unsupported export format: ${String(format)}`);
  }
}

/** The organisation block every export carries. */
/**
 * The provenance block printed on every export (§54).
 *
 * The organisation name comes from the SETTINGS profile, not from `ORG_NAME`. Once the
 * name is editable in the UI, an export that kept printing the env value would put a
 * different name on the file from the one on screen — a discrepancy in precisely the
 * field whose job is to say who produced the document. `ORG_NAME` remains the fallback
 * for a fresh installation that has not been through Settings yet.
 *
 * Async because it reads that profile, cached because an export of 20,000 rows should not
 * pay for a settings lookup it can make once a minute.
 */
export async function exportMeta(options: {
  branch?: string;
  from?: Date;
  to?: Date;
  asOf?: Date;
  generatedBy: string;
  filters?: Record<string, string | undefined>;
}): Promise<ExportSpec<unknown>["meta"]> {
  return { organisation: await organisationName(), ...options };
}

let cachedName: { value: string; at: number } | null = null;
const NAME_TTL_MS = 60_000;

async function organisationName(): Promise<string> {
  if (cachedName && Date.now() - cachedName.at < NAME_TTL_MS) return cachedName.value;

  try {
    const { getProfile } = await import("../modules/settings/settings.service.js");
    const profile = await getProfile();
    cachedName = { value: profile.displayName || profile.legalName, at: Date.now() };
  } catch {
    // A settings read must never be the reason an export fails — the name is a header.
    cachedName = { value: env.ORG_NAME, at: Date.now() };
  }

  return cachedName.value;
}

/** Called when the profile is saved, so the next export shows the new name immediately. */
export function invalidateOrganisationName(): void {
  cachedName = null;
}
