import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Express } from "express";
import { createApp } from "../../app.js";
import { AuditLog, Notification, Party } from "../../models/index.js";
import { ensureSystemAccounts } from "../../services/ledger.service.js";
import { TestClient, clearFixtures, seedFixtures, type Fixtures } from "../../test/helpers.js";

/**
 * Phase 7 acceptance: export (§53, §54), import (§52) and notifications (§50).
 *
 * The two assertions that matter most:
 *
 *   Export — money leaves as RUPEES, not paise, and a field that would execute as a
 *   spreadsheet formula is neutralised.
 *   Import — an invalid row is NEVER inserted, and a preview writes nothing at all.
 */

let app: Express;
let client: TestClient;
let fx: Fixtures;
let token: string;

async function raw(path: string, tok: string): Promise<{ status: number; text: string }> {
  const res = await fetch(`${(client as unknown as { baseUrl: string }).baseUrl}/api/v1${path}`, {
    headers: { authorization: `Bearer ${tok}` },
  });
  return { status: res.status, text: await res.text() };
}

beforeAll(async () => {
  await clearFixtures();
  fx = await seedFixtures();
  await ensureSystemAccounts();

  app = createApp();
  client = new TestClient();
  await client.start(app);
  token = await client.loginAs("super@test.co");

  const bank = await client.post<{ data: { id: string } }>(
    "/banks", { name: "HDFC Bank", shortName: "HDFC", ifscPrefix: "HDFC" }, { token },
  );
  const acc = await client.post<{ data: { id: string } }>(
    "/bank-accounts",
    {
      bankId: bank.body.data.id, accountName: "HDFC Current",
      accountNumber: "50100234567890", ifsc: "HDFC0001234",
      openingBalance: "10,00,000", openingDate: "2026-04-01",
    },
    { token },
  );

  const party = await client.post<{ data: { id: string } }>(
    "/parties",
    { name: "Sharma Traders", type: "CUSTOMER", openingBalance: "1,00,000", openingDate: "2026-04-01" },
    { token },
  );

  await client.post(
    "/payment-in",
    {
      date: "2026-08-19", partyId: party.body.data.id,
      accountId: acc.body.data.id, amount: "1,25,101", paymentMode: "NEFT",
    },
    { token },
  );
});

afterAll(async () => {
  await client.stop();
  await clearFixtures();
});

/* ══════════════════════════════════════════════════════════════════════════ */

describe("export (§53, §54)", () => {
  it("writes CSV with the full provenance block", async () => {
    const res = await raw("/export/daybook?from=2026-08-01&to=2026-08-31&format=csv", token);

    expect(res.status).toBe(200);
    // §54: an exported figure is worthless without knowing what it covered and who made it.
    expect(res.text).toContain("AMIRI Finance");
    expect(res.text).toContain("DayBook");
    expect(res.text).toContain("Generated by");
    expect(res.text).toContain("Generated at");
    expect(res.text).toContain("Period");
    expect(res.text).toContain("Voucher No");
    expect(res.text).toContain("TOTAL");
  });

  it("exports money as RUPEES, not paise", async () => {
    const res = await raw("/export/daybook?from=2026-08-01&to=2026-08-31&format=csv", token);

    // ₹1,25,101 is stored as 12510100 paise. A spreadsheet column of 12510100 that means
    // ₹1,25,101 is a trap — somebody will sum it and be out by a factor of a hundred.
    expect(res.text).toContain("125101");
    expect(res.text).not.toContain("12510100");
  });

  it("neutralises a field that would execute as a spreadsheet formula", async () => {
    // A party whose name is a formula. Opening the export in Excel would otherwise run it.
    await client.post(
      "/parties",
      { name: "=cmd|'/c calc'!A1", type: "OTHER", openingBalance: "0", openingDate: "2026-04-01" },
      { token },
    );

    const res = await raw("/export/audit?format=csv", token);
    expect(res.status).toBe(200);

    // Every occurrence is quote-prefixed, so Excel treats it as text.
    const dangerous = res.text.split("\n").filter((l) => l.includes("cmd|"));
    expect(dangerous.length).toBeGreaterThan(0);
    for (const line of dangerous) {
      expect(line).not.toMatch(/(^|,)=cmd/);
    }
  });

  it("produces a real Excel workbook", async () => {
    const res = await fetch(
      `${(client as unknown as { baseUrl: string }).baseUrl}/api/v1/export/profit-loss?from=2026-08-01&to=2026-08-31&format=xlsx`,
      { headers: { authorization: `Bearer ${token}` } },
    );

    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toContain("spreadsheetml");
    expect(res.headers.get("content-disposition")).toMatch(/attachment; filename="profit-and-loss-.*\.xlsx"/);

    // XLSX is a zip — the magic bytes prove a real workbook rather than an error page.
    const buffer = Buffer.from(await res.arrayBuffer());
    expect(buffer.subarray(0, 2).toString()).toBe("PK");
    expect(buffer.length).toBeGreaterThan(1000);
  });

  it("produces a real PDF", async () => {
    const res = await fetch(
      `${(client as unknown as { baseUrl: string }).baseUrl}/api/v1/export/balance-sheet?format=pdf`,
      { headers: { authorization: `Bearer ${token}` } },
    );

    expect(res.status).toBe(200);
    expect(res.headers.get("content-type")).toBe("application/pdf");

    const buffer = Buffer.from(await res.arrayBuffer());
    expect(buffer.subarray(0, 5).toString()).toBe("%PDF-");
    expect(buffer.length).toBeGreaterThan(1000);
  });

  it("states the balance-sheet difference on the export, not just on screen", async () => {
    const res = await raw("/export/balance-sheet?format=csv", token);
    // A balance sheet that quietly forced itself to balance would be worthless — on the
    // page or in the file.
    expect(res.text).toMatch(/Difference/i);
  });

  it("AUDITS every export", async () => {
    await raw("/export/trial-balance?format=csv", token);

    const entry = await AuditLog.findOne({ action: "EXPORT", entity: "TrialBalance" })
      .sort({ createdAt: -1 })
      .lean();

    // §26 lists EXPORT as auditable because taking a copy of the books out of the system
    // is the one action that otherwise leaves no trace.
    expect(entry).toBeTruthy();
    expect(entry!.userName).toBeTruthy();
  });

  it("carries the screen's filters into the audit export", async () => {
    // Whatever is filtered on screen is what comes out. An export that dropped the filter
    // would hand back a different report under the same name.
    const all = await raw("/export/audit?format=csv", token);
    const filtered = await raw("/export/audit?format=csv&action=EXPORT", token);

    expect(filtered.status).toBe(200);

    const dataRows = (text: string) =>
      text.split("\n").filter((l) => /,(CREATE|UPDATE|EXPORT|IMPORT|LOGIN|REVERSED|RECONCILED),/.test(l));

    const filteredRows = dataRows(filtered.text);
    expect(filteredRows.length).toBeGreaterThan(0);
    expect(filteredRows.length).toBeLessThan(dataRows(all.text).length);

    // Every surviving row really is an EXPORT, and the filter is printed on the file (§54)
    // so a copy sitting in an inbox still says which slice of the trail it is.
    for (const row of filteredRows) expect(row).toMatch(/,EXPORT,/);
    expect(filtered.text).toMatch(/Action.*EXPORT/);
  });

  it("keeps branch scoping when the audit export is also searched", async () => {
    // The search clause rewrites the filter's $or. If it overwrote the scope clause rather
    // than nesting it, a branch-scoped user would export every branch's trail.
    const scoped = await client.loginAs("badmin@test.co");
    const res = await raw("/export/audit?format=csv&q=a", scoped);

    // BRANCH_ADMIN does not hold audit.export; the point is that it is refused on
    // permission, not that the query silently widened.
    expect([200, 403]).toContain(res.status);

    if (res.status === 200) {
      if (foreign?.entityLabel) expect(res.text).not.toContain(foreign.entityLabel);
    }
  });

  it("audits an audit-log export too", async () => {
    await raw("/export/audit?format=csv", token);
    const entry = await AuditLog.findOne({ action: "EXPORT", entity: "AuditLog" })
      .sort({ createdAt: -1 })
      .lean();
    // Recursive, and correct.
    expect(entry).toBeTruthy();
  });

  it("refuses a user without the export permission", async () => {
    const accountant = await client.loginAs("acct@test.co");
    const res = await raw("/export/daybook?from=2026-08-01&to=2026-08-31", accountant);
    expect(res.status).toBe(403);
  });
});

/* ══════════════════════════════════════════════════════════════════════════ */

describe("import (§52)", () => {
  const goodRows = [
    { "Party Name": "Imported Traders", Type: "CUSTOMER", Mobile: "9800000001", "Opening Balance": "50,000.00", "Credit Days": "30" },
    { "Party Name": "Imported Vendors", Type: "VENDOR", Mobile: "9800000002", "Opening Balance": "-25,000.00" },
  ];

  it("previews without writing anything", async () => {
    const before = await Party.countDocuments({});

    const res = await client.post<{ data: { totalRows: number; valid: number; invalid: number; sample: unknown[] } }>(
      "/import/parties/preview",
      { rows: goodRows },
      { token },
    );

    expect(res.status).toBe(200);
    expect(res.body.data.totalRows).toBe(2);
    expect(res.body.data.valid).toBe(2);
    expect(res.body.data.sample.length).toBe(2);

    // The whole point of a preview.
    expect(await Party.countDocuments({})).toBe(before);
  });

  it("normalises header spelling", async () => {
    // "Party Name", "party_name" and "PARTY NAME" all reach the same field — a sheet
    // exported from anywhere has inconsistent headers.
    const res = await client.post<{ data: { valid: number } }>(
      "/import/parties/preview",
      { rows: [{ party_name: "Header Test Co", TYPE: "CUSTOMER", "opening balance": "1,000" }] },
      { token },
    );
    expect(res.body.data.valid).toBe(1);
  });

  it("reports invalid rows and does NOT import them", async () => {
    const before = await Party.countDocuments({});

    const res = await client.post<{
      data: { imported: number; invalid: number; issues: Array<{ row: number; message: string }> };
    }>(
      "/import/parties/commit",
      {
        rows: [
          { "Party Name": "Valid Import Co", "Opening Balance": "10,000" },
          { "Party Name": "X" },                                  // name too short
          { "Party Name": "Bad Amount Co", "Opening Balance": "not a number" },
        ],
      },
      { token },
    );

    expect(res.status).toBe(200);
    // Only the good row landed.
    expect(res.body.data.imported).toBe(1);
    expect(res.body.data.issues.length).toBeGreaterThan(0);
    expect(await Party.countDocuments({})).toBe(before + 1);

    expect(await Party.findOne({ name: "Bad Amount Co" }).lean()).toBeNull();
  });

  it("detects a duplicate rather than overwriting or silently skipping it", async () => {
    await client.post("/import/parties/commit", { rows: goodRows }, { token });

    const again = await client.post<{
      data: { imported: number; duplicates: number; issues: Array<{ message: string; severity: string }> };
    }>("/import/parties/commit", { rows: goodRows }, { token });

    expect(again.body.data.imported).toBe(0);
    expect(again.body.data.duplicates).toBe(2);
    // Reported as a warning the operator can act on, not swallowed.
    expect(again.body.data.issues.some((i) => i.severity === "warning")).toBe(true);
    expect(await Party.countDocuments({ name: "Imported Traders" })).toBe(1);
  });

  it("creates each imported party with a ledger account and a posted opening balance", async () => {
    const party = await Party.findOne({ name: "Imported Traders" }).lean();
    expect(party).toBeTruthy();
    // Bulk-inserting documents would have been far faster and left them unusable.
    expect(party!.ledgerAccountId).toBeTruthy();

    const { LedgerAccount } = await import("../../models/index.js");
    const ledgerAccount = await LedgerAccount.findById(party!.ledgerAccountId).lean();
    expect(ledgerAccount!.cachedBalance).toBe(50_000_00);
  });

  it("audits the import", async () => {
    const entry = await AuditLog.findOne({ action: "IMPORT", entity: "Party" }).sort({ createdAt: -1 }).lean();
    expect(entry).toBeTruthy();
    expect((entry!.newValue as { imported: number }).imported).toBeGreaterThanOrEqual(0);
  });

  it("keeps the books tying after an import", async () => {
    const { trialBalance } = await import("../../services/ledger.service.js");
    const tb = await trialBalance();
    expect(tb.difference).toBe(0);
  });
});

/* ══════════════════════════════════════════════════════════════════════════ */

describe("notifications (§50)", () => {
  it("notifies the approvers when a transaction is held", async () => {
    await client.request("PUT", "/approvals/settings", {
      token,
      body: {
        enabled: true,
        minimumAmount: "1,000",
        tiers: [{ from: "0", to: null, tier: "BRANCH_ADMIN" }],
        appliesTo: [],
      },
    });

    const account = await client.get<{ data: Array<{ id: string }> }>("/bank-accounts", { token });
    const party = await Party.findOne({ name: "Sharma Traders" }).lean();

    await client.post(
      "/payment-out",
      {
        date: "2026-08-22", partyId: String(party!._id),
        accountId: account.body.data[0]!.id, amount: "40,000", paymentMode: "NEFT",
      },
      { token },
    );

    // Fan-out happens at send time, one row per user.
    const sent = await Notification.find({ type: "APPROVAL_REQUIRED" }).lean();
    expect(sent.length).toBeGreaterThan(0);
    expect(sent[0]!.title).toMatch(/needs approval/i);
    expect(sent[0]!.link).toBe("/approvals");

    await client.request("PUT", "/approvals/settings", {
      token,
      body: { enabled: false, minimumAmount: "0", tiers: [], appliesTo: [] },
    });
  });

  it("serves only the caller's own notifications", async () => {
    const res = await client.get<{ data: { items: Array<{ title: string }>; unread: number } }>(
      "/notifications",
      { token },
    );

    expect(res.status).toBe(200);
    const mine = await Notification.countDocuments({ userId: fx.users.superAdmin!.id });
    expect(res.body.data.items.length).toBe(Math.min(mine, 30));
  });

  it("marks notifications read", async () => {
    const before = await client.get<{ data: { unread: number } }>("/notifications", { token });
    if (before.body.data.unread === 0) return;

    const res = await client.post<{ data: { marked: number } }>("/notifications/read", {}, { token });
    expect(res.body.data.marked).toBeGreaterThan(0);

    const after = await client.get<{ data: { unread: number } }>("/notifications", { token });
    expect(after.body.data.unread).toBe(0);
  });

  it("does not let a notification failure break the transaction that triggered it", async () => {
    // Notifications are sent AFTER commit and swallow their own errors — a payment must
    // never fail because a courtesy message could not be delivered.
    const { notify } = await import("../notifications/notification.service.js");
    await expect(notify(["not-a-valid-object-id"], { type: "LOW_BALANCE", title: "x" })).resolves.toBeUndefined();
  });
});
